In [1]:
import datetime
import time
from scipy.spatial import distance as dist
from imutils.video import VideoStream
from imutils import face_utils
from threading import Thread
import numpy as np
import argparse
import imutils
import time
import dlib
import cv2
import os
from deepface import DeepFace
import pyttsx3
from quoteslist import anger_quotes, sadness_quotes
import random


In [2]:
def eye_aspect_ratio(eye):
    A = dist.euclidean(eye[1], eye[5])
    B = dist.euclidean(eye[2], eye[4])

    C = dist.euclidean(eye[0], eye[3])

    ear = (A + B) / (2.0 * C)

    return ear


In [3]:
def final_ear(shape):
    (lStart, lEnd) = face_utils.FACIAL_LANDMARKS_IDXS["left_eye"]
    (rStart, rEnd) = face_utils.FACIAL_LANDMARKS_IDXS["right_eye"]

    leftEye = shape[lStart:lEnd]
    rightEye = shape[rStart:rEnd]

    leftEAR = eye_aspect_ratio(leftEye)
    rightEAR = eye_aspect_ratio(rightEye)

    ear = (leftEAR + rightEAR) / 2.0
    return (ear, leftEye, rightEye)


In [4]:
def lip_distance(shape):
    top_lip = shape[50:53]
    top_lip = np.concatenate((top_lip, shape[61:64]))

    low_lip = shape[56:59]
    low_lip = np.concatenate((low_lip, shape[65:68]))

    top_mean = np.mean(top_lip, axis=0)
    low_mean = np.mean(low_lip, axis=0)

    distance = abs(top_mean[1] - low_mean[1])
    return distance

In [5]:
def getemotion(frame):
    try:
        face_analysis = DeepFace.analyze(frame,actions = ['emotion'])
        dominant_emotion = face_analysis[0]['dominant_emotion']
        #print(face_analysis[0])
        emotion_value = face_analysis[0]['emotion'][dominant_emotion]

        #print(emotion_value)
        if emotion_value >= 50:
            print('a major emotion')
            #time.sleep(3)
            return dominant_emotion
            
        else:
            print('no major emotion')
            #time.sleep(3)
            return False
        
    except:
        return False
    


In [6]:
def getstatus(frame):
    global COUNTER
    global EYE_AR_THRESH
    global EYE_AR_CONSEC_FRAMES
    global YAWN_THRESH
    sleepy = False
    yawn = False
    dominant_emotion = getemotion(frame)
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    rects = detector.detectMultiScale(gray, scaleFactor=1.1, 
		minNeighbors=5, minSize=(30, 30),
		flags=cv2.CASCADE_SCALE_IMAGE)
    print(rects)
    for (x, y, w, h) in rects:
        rect = dlib.rectangle(int(x), int(y), int(x + w),int(y + h))
        
        shape = predictor(gray, rect)
        shape = face_utils.shape_to_np(shape)

        eye = final_ear(shape)
        ear = eye[0]
        leftEye = eye [1]
        rightEye = eye[2]

        distance = lip_distance(shape)

        leftEyeHull = cv2.convexHull(leftEye)
        rightEyeHull = cv2.convexHull(rightEye)
        cv2.drawContours(frame, [leftEyeHull], -1, (0, 255, 0), 1)
        cv2.drawContours(frame, [rightEyeHull], -1, (0, 255, 0), 1)

        lip = shape[48:60]
        cv2.drawContours(frame, [lip], -1, (0, 255, 0), 1)

        if ear < EYE_AR_THRESH:
            COUNTER += 1
            #print('sewy')

            if COUNTER >= EYE_AR_CONSEC_FRAMES:
                #print('oki')
                if sleepy == False:
                    sleepy = True
                    #t = Thread(target=alarm, args=('wake up sir',))
                    #t.deamon = True
                    #t.start()

                cv2.putText(frame, "DROWSINESS ALERT!", (10, 30),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)

        else:
            COUNTER = 0
            sleepy = False

        if (distance > YAWN_THRESH):
                cv2.putText(frame, "Yawn Alert", (10, 30),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
                if yawn == False and saying == False:
                    yawn = True
                    #t = Thread(target=alarm, args=('take some fresh air sir',))
                    #t.deamon = True
                    #t.start()
        else:
            yawn = False

        cv2.putText(frame, "EAR: {:.2f}".format(ear), (300, 30),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
        cv2.putText(frame, "YAWN: {:.2f}".format(distance), (300, 60),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
        print(yawn,sleepy)

        
        
    final_data = {'sleepy': sleepy,
                      'yawn': yawn,
                      'dominant emotion': dominant_emotion}
    print(final_data, 'kasgdagdajd')
    return final_data
    

In [7]:
detector = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")    #Faster but less accurate
predictor = dlib.shape_predictor('shape_predictor_68_face_landmarks.dat')

engine = pyttsx3.init()
#ap = argparse.ArgumentParser()
#ap.add_argument("-w", "--webcam", type=int, default=0,
                #help="index of webcam on system")
#args = vars(ap.parse_args())

EYE_AR_THRESH = 0.3
EYE_AR_CONSEC_FRAMES = 30
YAWN_THRESH = 20
sleepy = False
yawn = False
saying = False
COUNTER = 0
#vs = VideoStream(0).start()
cap = cv2.VideoCapture(0)
timesincelastreport = time.time()
while True:
    #frame = vs.read()
    ret, frame = cap.read()
    frame = imutils.resize(frame, width=450)
    status = getstatus(frame)
    
    #print(status)
    emotion = status.get('dominant emotion')
    sleepy = status.get('sleepy')
    yawn = status.get('yawn')
    cv2.imshow("Frame", frame)
    #key = cv2.waitKey(1) & 0xFF

    #print(COUNTER)

    other_emotion = False
    


    if emotion != False:
        if timesincelastreport+5 <= time.time():
            if emotion == 'angry':
                other_emotion = True
                engine.say('please calm down')
                engine.runAndWait()
                engine.say(random.choice(anger_quotes))
                engine.runAndWait()
                timesincelastreport = time.time()
                #time.sleep(5)
            elif emotion == 'sad':
                #time.sleep(0.5)

                other_emotion = True
                engine.say('dont be sad')
                engine.runAndWait()
                engine.say(random.choice(sadness_quotes))
                engine.runAndWait()
                timesincelastreport = time.time()
                #time.sleep(5)
            # elif emotion == 'fear':
                # other_emotion = True
                # engine.say('dont be scared')
                # engine.runAndWait()
                # time.sleep(5)
            #elif emotion != 'neutral':
                #other_emotion == True
                #time.sleep(5)
            else:
                pass

    if sleepy  == True and other_emotion == False and timesincelastreport+5 <= time.time():
        engine.say('feeling sleepy? drink some water or have a coffee')
        engine.runAndWait()
        sleepy = False
        yawn = False
        print('slpehf')
        timesincelastreport = time.time()
        #time.sleep(5)

        print(other_emotion)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

    print(sleepy,yawn)
cap.release()
cv2.destroyAllWindows()

2023-12-25 21:22:25.731 Python[70172:2369434] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.


()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  5.88it/s]


a major emotion
[[215 103  57  57]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.88it/s]


no major emotion
[[182  91  60  60]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.17it/s]


a major emotion
[[163  85  63  63]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 34.78it/s]


a major emotion
[[142  77  66  66]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.21it/s]

a major emotion


[[125  70  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 33.21it/s]


a major emotion
[[118  62  75  75]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.13it/s]


a major emotion
[[127  62  73  73]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.80it/s]


a major emotion
[[135  60  77  77]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 41.32it/s]


a major emotion
[[147  61  78  78]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.80it/s]


a major emotion
[[160  63  79  79]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.37it/s]


a major emotion
[[173  67  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.93it/s]


a major emotion
[[181  68  79  79]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.16it/s]

a major emotion
[[185  69  78  78]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False



Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.30it/s]

a major emotion
[[189  70  77  77]]


False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.98it/s]


a major emotion
[[194  72  75  75]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 41.55it/s]


no major emotion
[[193  73  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.27it/s]


no major emotion
[[195  74  74  74]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 41.06it/s]


a major emotion
[[194  75  73  73]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 31.32it/s]

no major emotion


[[192  75  74  74]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.76it/s]


no major emotion
[[191  77  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.38it/s]


a major emotion
[[192  78  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.11it/s]


a major emotion
[[191  78  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.70it/s]


no major emotion
[[191  79  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 41.32it/s]


a major emotion
[[191  79  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.82it/s]


a major emotion
[[190  79  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.85it/s]


a major emotion
[[190  80  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.56it/s]


no major emotion
[[190  81  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 41.06it/s]


no major emotion
[[188  79  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.77it/s]


no major emotion
[[187  78  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 32.60it/s]

no major emotion
[[189  80  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.22it/s]


no major emotion
[[188  80  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.31it/s]


a major emotion
[[187  79  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.98it/s]


a major emotion
[[187  78  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.09it/s]


a major emotion
[[187  78  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.71it/s]


a major emotion
[[186  78  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.75it/s]


no major emotion
[[187  78  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.38it/s]


a major emotion
[[186  78  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.71it/s]

no major emotion
[[187  78  70  70]]


False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.10it/s]


no major emotion
[[186  77  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.91it/s]

a major emotion
[[186  77  71  71]]


False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 30.83it/s]

a major emotion


[[185  77  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.54it/s]


no major emotion
[[186  77  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.85it/s]


a major emotion
[[184  77  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.43it/s]


a major emotion
[[185  78  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.00it/s]

a major emotion
[[186  79  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.33it/s]


a major emotion
[[185  78  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.28it/s]


no major emotion
[[185  78  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.92it/s]

a major emotion
[[185  79  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False



Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.31it/s]


a major emotion
[[185  79  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 30.46it/s]

a major emotion
[[186  80  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.18it/s]


no major emotion
[[185  79  73  73]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.28it/s]


a major emotion
[[185  79  71  71]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.27it/s]


a major emotion
[[187  80  70  70]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.91it/s]


a major emotion
[[188  80  70  70]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.34it/s]


no major emotion
[[188  79  70  70]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': False} kasgdagdajd
True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.45it/s]


a major emotion
[[187  79  72  72]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.85it/s]


no major emotion
[[187  79  70  70]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': False} kasgdagdajd
True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.56it/s]


no major emotion
[[187  79  71  71]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': False} kasgdagdajd
slpehf
False
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.61it/s]


a major emotion
[[192  75  69  69]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.83it/s]


a major emotion
[[192  75  69  69]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 30.85it/s]


a major emotion
[[193  76  68  68]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.72it/s]


a major emotion
[[192  75  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.36it/s]


a major emotion
[[190  75  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.44it/s]


a major emotion
[[190  75  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.04it/s]


a major emotion
[[191  75  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.16it/s]

a major emotion
[[191  75  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.78it/s]


no major emotion
[[190  75  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.80it/s]


a major emotion
[[190  75  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.83it/s]


a major emotion
[[191  76  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.36it/s]

a major emotion
[[191  76  68  68]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 30.52it/s]


a major emotion
[[191  76  68  68]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.74it/s]


a major emotion
[[192  77  67  67]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.58it/s]


a major emotion
[[191  77  68  68]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.98it/s]


a major emotion
[[191  77  68  68]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.64it/s]


a major emotion
[[189  76  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.63it/s]


a major emotion
[[189  76  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.61it/s]


a major emotion
[[188  75  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.12it/s]


a major emotion
[[189  76  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.55it/s]


a major emotion
[[188  75  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.60it/s]

a major emotion
[[188  75  71  71]]


False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.96it/s]


a major emotion
[[188  75  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.08it/s]


a major emotion
[[188  75  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.77it/s]


a major emotion
[[188  75  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.01it/s]


no major emotion
[[188  76  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.75it/s]


no major emotion
[[188  76  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.51it/s]


a major emotion
[[189  76  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.74it/s]


a major emotion
[[188  74  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'surprise'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.54it/s]


a major emotion
[[187  73  73  73]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'surprise'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.17it/s]


a major emotion
[[188  73  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'surprise'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.16it/s]


a major emotion
[[188  73  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'surprise'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.46it/s]


a major emotion
[[187  73  73  73]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'surprise'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.75it/s]

a major emotion
[[188  73  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'surprise'} kasgdagdajd
False False



Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.45it/s]

a major emotion
[[188  74  71  71]]


False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'surprise'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.60it/s]


no major emotion
[[189  74  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.32it/s]


a major emotion
[[187  73  73  73]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.05it/s]

a major emotion
[[188  73  73  73]]


False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.43it/s]


a major emotion
[[187  74  73  73]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.90it/s]

a major emotion
[[188  74  72  72]]


False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.54it/s]


a major emotion
[[188  75  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.43it/s]


a major emotion
[[187  74  73  73]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.24it/s]


a major emotion
[[187  74  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.91it/s]

no major emotion
[[188  75  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.18it/s]


a major emotion
[[189  76  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.71it/s]


a major emotion
[[189  76  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.50it/s]


a major emotion
[[188  75  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.71it/s]


a major emotion
[[187  75  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.47it/s]


a major emotion
[[188  75  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.85it/s]


a major emotion
[[188  75  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.19it/s]

a major emotion


[[189  75  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.46it/s]


a major emotion
[[189  76  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.25it/s]


a major emotion
[[188  75  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.62it/s]


a major emotion
[[189  75  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.31it/s]


a major emotion
[[189  76  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.91it/s]


a major emotion
[[189  76  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.42it/s]


no major emotion
[[189  76  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 35.82it/s]


a major emotion
[[190  76  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.66it/s]


no major emotion
[[190  78  68  68]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.90it/s]

no major emotion
[[191  79  67  67]]


False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.63it/s]


a major emotion
[[191  78  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.61it/s]

no major emotion
[[191  77  68  68]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 30.11it/s]


no major emotion
[[189  77  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.40it/s]


a major emotion
[[189  78  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.26it/s]


a major emotion
[[189  80  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.31it/s]


a major emotion
[[189  82  73  73]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.32it/s]


a major emotion
[[190  84  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.29it/s]


a major emotion
[[190  84  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.58it/s]


a major emotion
[[189  82  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 30.99it/s]


a major emotion
[[182  85  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.07it/s]

no major emotion
[[181  85  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False



Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.60it/s]


no major emotion
[[182  86  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 34.37it/s]


a major emotion
[[181  86  73  73]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 35.43it/s]


no major emotion
[[184  85  74  74]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.29it/s]


a major emotion
[[189  85  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 35.53it/s]


a major emotion
[[193  84  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.03it/s]


a major emotion
[[197  85  73  73]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.41it/s]

a major emotion
[[202  88  71  71]]


False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 32.98it/s]

a major emotion


[[200  85  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.82it/s]


no major emotion
[[200  88  75  75]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 29.63it/s]


no major emotion
[[196  89  75  75]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 33.10it/s]


no major emotion
[[189  93  74  74]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.62it/s]


no major emotion
[[186  94  75  75]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.65it/s]


no major emotion
[[189  97  74  74]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.34it/s]


a major emotion
[[192  97  77  77]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.84it/s]


no major emotion
[[202 101  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.49it/s]


a major emotion
[[209 102  75  75]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 35.80it/s]


a major emotion
[[216 102  77  77]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.57it/s]

a major emotion
[[219 103  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.74it/s]


a major emotion
[[220  96  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 33.73it/s]


a major emotion
[[219  82  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 33.11it/s]


no major emotion
[[217  63  75  75]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.62it/s]


a major emotion
[[203  67  87  87]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 35.33it/s]


no major emotion
[[197  71  91  91]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.92it/s]


a major emotion
[[194  71  91  91]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.19it/s]


a major emotion
[[187  80  94  94]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.97it/s]


a major emotion
[[186  81  91  91]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.59it/s]


a major emotion
[[187  78  93  93]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'surprise'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 32.40it/s]

a major emotion


[[188  82  91  91]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 35.46it/s]


a major emotion
[[180  74 102 102]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.03it/s]


no major emotion
[[182  78 102 102]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.98it/s]


a major emotion
[[179  72 104 104]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.23it/s]


a major emotion
[[177  72 103 103]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.43it/s]


a major emotion
[[179  72 107 107]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.56it/s]


a major emotion
[[175  69 108 108]]
True False
{'sleepy': False, 'yawn': True, 'dominant emotion': 'happy'} kasgdagdajd
False True


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 34.93it/s]

a major emotion
[[180  78  97  97]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.18it/s]


a major emotion
[[180  70 109 109]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.99it/s]

a major emotion


[[183  56 115 115]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy':

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.41it/s]


a major emotion
[[225  50  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.85it/s]

a major emotion
[[215  49  74  74]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False



Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 35.80it/s]

no major emotion
[[210  50  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False



Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 31.84it/s]


a major emotion
[[204  51  74  74]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.70it/s]


a major emotion
[[196  51  78  78]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 34.40it/s]


a major emotion
[[194  51  77  77]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.79it/s]


a major emotion
[[192  52  78  78]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.51it/s]


a major emotion
[[192  54  77  77]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.32it/s]


no major emotion
[[194  57  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 32.62it/s]


a major emotion
[[193  60  78  78]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.97it/s]


a major emotion
[[195  64  77  77]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 34.77it/s]

no major emotion


[[194  68  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 35.92it/s]


a major emotion
[[193  72  75  75]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.11it/s]


a major emotion
[[194  75  74  74]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 35.64it/s]


a major emotion
[[193  75  75  75]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 35.59it/s]


a major emotion
[[191  75  75  75]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.81it/s]


a major emotion
[[191  76  75  75]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.63it/s]


a major emotion
[[190  75  74  74]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.20it/s]


no major emotion
[[192  77  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 35.82it/s]

a major emotion
[[192  78  68  68]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False

 False
[[193  80  67  67]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 34.48it/s]


a major emotion
[[192  80  66  66]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False
[[192  80  67  67]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[192  80  68  68]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[192  79  67  67]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[192  79  67  67]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[192  80  66  66]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[188  76  73  73]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False 

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.69it/s]


a major emotion
[[190  77  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.18it/s]

no major emotion
[[192  79  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.72it/s]


no major emotion
[[192  79  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.34it/s]


no major emotion
[[191  79  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.19it/s]


a major emotion
[[191  79  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.42it/s]


no major emotion
[[191  78  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 34.16it/s]


a major emotion
[[191  78  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.03it/s]


no major emotion
[[191  80  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 27.25it/s]

no major emotion
[[191  80  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 35.41it/s]


no major emotion
[[189  80  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.64it/s]


no major emotion
[[189  80  73  73]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.73it/s]


no major emotion
[[190  81  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 35.22it/s]


no major emotion
[[191  82  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 32.94it/s]


a major emotion
[[191  81  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.89it/s]


a major emotion
[[184  73  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.00it/s]


a major emotion
[[184  71  74  74]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.41it/s]


a major emotion
[[183  70  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 29.97it/s]


no major emotion
[[185  72  73  73]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.25it/s]


a major emotion
[[186  75  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.44it/s]


a major emotion
[[186  76  73  73]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.95it/s]


no major emotion
[[188  77  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.80it/s]


no major emotion
[[189  77  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.60it/s]


no major emotion
[[191  78  67  67]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.53it/s]


no major emotion
[[189  76  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.75it/s]

no major emotion
[[189  75  72  72]]


False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 32.23it/s]


no major emotion
[[190  76  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.69it/s]


no major emotion
[[190  75  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.23it/s]


no major emotion
[[191  75  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.14it/s]


no major emotion
[[191  75  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.22it/s]


no major emotion
[[191  75  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 35.45it/s]


no major emotion
[[191  75  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.90it/s]


no major emotion
[[191  76  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.03it/s]


no major emotion
[[191  75  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.54it/s]


no major emotion
[[191  76  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.60it/s]


no major emotion
[[192  76  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.50it/s]


no major emotion
[[191  77  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 34.93it/s]

no major emotion
[[190  78  70  70]]


False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.28it/s]


no major emotion
[[190  78  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.41it/s]


a major emotion
[[188  77  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.78it/s]


no major emotion
[[189  78  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.41it/s]

a major emotion
[[189  78  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.82it/s]

a major emotion
[[187  78  68  68]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.32it/s]

no major emotion
[[186  77  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.25it/s]


no major emotion
[[185  77  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.81it/s]


a major emotion
[[185  77  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.47it/s]


a major emotion
[[186  77  67  67]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.24it/s]

a major emotion
[[183  74  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.53it/s]


a major emotion
[[184  74  68  68]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.63it/s]

a major emotion
[[182  74  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.73it/s]

a major emotion
[[183  75  67  67]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'angry'} kasgdagdajd
False False



Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.34it/s]


no major emotion
[[182  75  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 31.81it/s]

no major emotion
[[181  75  68  68]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.49it/s]


no major emotion
[[182  76  67  67]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 35.15it/s]


no major emotion
[[182  77  67  67]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.72it/s]


no major emotion
[[183  77  66  66]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 41.13it/s]


no major emotion
[[183  77  66  66]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.56it/s]


a major emotion
[[184  77  67  67]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.72it/s]


a major emotion
[[184  77  67  67]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.28it/s]

a major emotion
[[185  77  67  67]]


False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.87it/s]


a major emotion
[[186  77  66  66]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.31it/s]

a major emotion
[[187  76  67  67]]


False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.02it/s]


a major emotion
[[186  75  68  68]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.77it/s]


a major emotion
[[187  76  66  66]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.24it/s]


a major emotion
[[186  75  67  67]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.46it/s]

a major emotion
[[185  74  68  68]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
True False



Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.59it/s]

a major emotion
[[185  74  66  66]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
True False



Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.95it/s]

a major emotion
[[184  73  68  68]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd


True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.56it/s]


a major emotion
[[184  73  67  67]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.45it/s]

a major emotion
[[183  73  66  66]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd


True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.86it/s]

a major emotion
[[182  72  65  65]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd


True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.72it/s]


no major emotion
[[184  73  64  64]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': False} kasgdagdajd
True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.13it/s]


a major emotion
[[180  71  70  70]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 30.50it/s]

a major emotion
[[181  72  67  67]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd


True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.93it/s]


no major emotion
[[181  71  67  67]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': False} kasgdagdajd
True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.51it/s]


no major emotion
[[180  72  68  68]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': False} kasgdagdajd
True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.98it/s]


a major emotion
[[179  72  70  70]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.96it/s]


a major emotion
[[179  72  71  71]]
False True
{'sleepy': True, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
True False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.32it/s]


a major emotion
[[180  73  68  68]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.28it/s]


no major emotion
[[180  74  67  67]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.45it/s]


a major emotion
[[181  74  68  68]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.16it/s]


a major emotion
[[181  73  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.58it/s]


a major emotion
[[180  73  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.59it/s]

a major emotion
[[179  73  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 32.46it/s]


a major emotion
[[180  73  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.54it/s]


a major emotion
[[180  74  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.04it/s]


a major emotion
[[178  71  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.57it/s]


a major emotion
[[179  72  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.81it/s]


a major emotion
[[178  71  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.47it/s]


a major emotion
[[178  69  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.88it/s]


a major emotion
[[188  69  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00,  6.92it/s]


a major emotion
[[188  69  75  75]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.65it/s]


a major emotion
[[188  69  75  75]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.98it/s]


a major emotion
[[187  69  75  75]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.56it/s]


a major emotion
[[186  69  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 29.24it/s]


a major emotion
[[186  69  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.94it/s]


a major emotion
[[186  69  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.42it/s]


a major emotion
[[184  67  78  78]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.55it/s]


a major emotion
[[185  67  77  77]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 41.23it/s]


a major emotion
[[186  59  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False
[[184  51  82  82]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[183  51  80  80]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.74it/s]


a major emotion
[[181  53  84  84]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.58it/s]


a major emotion
[[182  56  85  85]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.73it/s]

no major emotion
[[182  65  86  86]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


[[189  76  82  82]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.27it/s]


a major emotion
[[192  78  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.12it/s]


a major emotion
[[190  80  73  73]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[188  87  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[184  88  74  74]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[185  89  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[186  89  71  71]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion'

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.25it/s]

a major emotion
[[185  84  77  77]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False



Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.06it/s]

no major emotion
[[181  83  77  77]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 31.23it/s]


a major emotion
[[176  84  79  79]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 41.56it/s]

a major emotion
[[175  83  82  82]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False



Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.25it/s]


a major emotion
[[178  70  82  82]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 41.94it/s]


a major emotion
[[183  66  85  85]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 41.18it/s]

no major emotion
[[188  79  87  87]]


False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 41.74it/s]


a major emotion
[[189  98  84  84]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.16it/s]


a major emotion
[[183  92  82  82]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.03it/s]


a major emotion
[[182  84  81  81]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'surprise'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.63it/s]


a major emotion
[[187  79  84  84]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.44it/s]

no major emotion
[[200  89  81  81]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False



Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.65it/s]


a major emotion
[[210  93  85  85]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.86it/s]


no major emotion
[[206  89  85  85]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.71it/s]


no major emotion
[[200  83  80  80]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.00it/s]


a major emotion
[[188  77  82  82]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.16it/s]


a major emotion
[[182  79  82  82]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.43it/s]

a major emotion
[[178  83  87  87]]


False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.38it/s]


a major emotion
[[186  80  83  83]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.73it/s]


no major emotion
[[196  74  85  85]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.57it/s]


no major emotion
[[210  73  81  81]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[224  76  79  79]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.93it/s]


a major emotion
[[231  78  80  80]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.36it/s]


a major emotion
[[237  86  83  83]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.03it/s]


a major emotion
[[231  85  83  83]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 29.96it/s]


no major emotion
[[215  81  80  80]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.46it/s]


a major emotion
[[193  79  75  75]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False
[[167  78  82  82]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.74it/s]


a major emotion
[[162  82  80  80]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.93it/s]


no major emotion
[[159  80  83  83]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.85it/s]

a major emotion
[[171  80  77  77]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd


False False
[[184  80  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[223  91  80  80]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[228  91  74  74]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[218  85  77  77]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.17it/s]


a major emotion
[[208  83  74  74]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.48it/s]

no major emotion
[[188  83  78  78]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 41.24it/s]


a major emotion
[[178  83  83  83]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 30.25it/s]

a major emotion
[[189  80  81  81]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd


False False
[[211  88  76  76]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[218  92  79  79]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.75it/s]


no major emotion
[[222  92  84  84]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.12it/s]

no major emotion
[[212  91  79  79]]


False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.93it/s]


a major emotion
[[193  86  79  79]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.58it/s]


a major emotion
[[175  90  78  78]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 41.31it/s]

a major emotion
[[174  87  78  78]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 41.27it/s]


a major emotion
[[188  85  72  72]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.83it/s]


a major emotion
[[197  86  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 30.49it/s]


a major emotion
[[202  87  67  67]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.26it/s]


a major emotion
[[208  89  66  66]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.93it/s]


a major emotion
[[208  89  66  66]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.53it/s]


no major emotion
[[208  90  64  64]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.84it/s]


no major emotion
[[208  91  63  63]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[207  91  63  63]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[205  90  65  65]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[205  92  65  65]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.32it/s]


no major emotion
[[206  93  64  64]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 36.19it/s]

a major emotion
[[203  92  66  66]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.78it/s]


a major emotion
[[176  32  86  86]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.18it/s]


no major emotion
[[168  27  93  93]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.68it/s]


no major emotion
[[159  25  95  95]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.85it/s]


a major emotion
[[150  21 102 102]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False Fal

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.92it/s]

a major emotion
[[152  59  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'sad'} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.00it/s]

no major emotion
[[157  45 103 103]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd


False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.37it/s]

a major emotion
[[152  35 204 204]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd


False False
[[169  25  91  91]
 [164  26 183 183]]
False False
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[178  28  78  78]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.73it/s]

a major emotion
[[183  52 107 107]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


[[188  71  66  66]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[203  95  75  75]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.21it/s]

a major emotion
[[203 104  69  69]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[191  77  62  62]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


[[189  64  61  61]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[189  58  66  66]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.69it/s]

a major emotion
[[202 102  66  66]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False
[[205 100  66  66]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd


False False
[[208  77  70  70]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[210  74  73  73]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[199  82  85  85]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[202  70  88  88]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[207  69  82  82]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
[[203  73  95  95]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': Fa

Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 38.36it/s]

a major emotion
[[220  84  80  80]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False
()
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd


False False
[[213 104  86  86]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.72it/s]


a major emotion
[[210 102  88  88]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.53it/s]


a major emotion
[[206  95  90  90]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.43it/s]


a major emotion
[[194  93  93  93]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'happy'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.75it/s]


a major emotion
[[184  98  91  91]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'fear'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.11it/s]


no major emotion
[[172  95  93  93]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 29.89it/s]


a major emotion
[[160  79  97  97]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 37.68it/s]


no major emotion
[[156  61  87  87]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': False} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.71it/s]


a major emotion
[[152  53  89  89]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.05it/s]


a major emotion
[[156  52  88  88]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 40.35it/s]


a major emotion
[[159  51  85  85]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
False False


Action: emotion: 100%|██████████| 1/1 [00:00<00:00, 39.76it/s]


a major emotion
[[161  48  85  85]]
False False
{'sleepy': False, 'yawn': False, 'dominant emotion': 'neutral'} kasgdagdajd
